# Generated by Django 3.2.12 on 2023-05-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userImage',
            field=models.ImageField(default="<i class='fa fa-user'></i>", upload_to='userImage/'),
        ),
    ]
